### ISSUE TITLE
Error on startup & crates having to be replaced every time I restart my server!

### ISSUE THREAD

**Issue by Justsean2** [ConnorLinfoot/CratesPlus#813]
I get a weird message in console when I start up my server and after each reboot on my server I have to remove the old crates and place down new ones.

Error: https://pastebin.com/8GRWLT26
Config: https://pastebin.com/dKUdgp2v

**Comment by Croug** [comment]
I am getting the same issue on my server, maybe this is related to issue #323 It's an old issue, but maybe solved the same way? I'll have to test it out.

**Comment by Justsean2** [comment]
@Croug Hey! I've tried a few times, no success. So I resulted to asking for help here! I appreciate it!

**Comment by Croug** [comment]
@Justsean2 I was able to resolve the issue by deleting the data.yml and replacing the crates, or at least it appears fixed right now, I restarted the server and my crates persisted, but still whatever issue caused the crates to become bugged in the first place breaking the data.yml issue should be fixed although I don't even know where in my logs I would look for the error.

**Comment by Justsean2** [comment]
@Croug Interesting.. I tried again and still no luck hopefully the devs can help me out! Best of luck to you & your server!

**Comment by Croug** [comment]
Thank you! Best of luck to you aswell!

**Comment by Croug** [comment]
@Justsean2 the issue started popping back up, as a temporary workaround I have been able to get the crates to show back up by reloading it with plugman.

**Comment by Justsean2** [comment]
Interesting, I've tried everything under the sun at this point lol, I'm just hoping that the developer can help out.

**Comment by sebastiantho** [comment]
I'm getting the same issue too.

**Comment by Justsean2** [comment]
Interesting. I wonder what's causing it.

**Comment by KeyurNaidu** [comment]
Hey, has this been fixed for you? I'm having the exact same issue and it's very annoying! 

Hopefully, the developer can fix this as soon as possible.

**Comment by Justsean2** [comment]
@KeyurNaidu This has not been attended to as of yet, I hope someone can help soon!

**Comment by KeyurNaidu** [comment]
> @KeyurNaidu This has not been attended to as of yet, I hope someone can help soon!

Any updates?
